
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-RPL1
 */
public class spp extends javax.swing.JFrame {
    HashMap<Integer, String> idJurusan= new HashMap<>();
    HashMap<Integer, String> idSiswa= new HashMap<>();
    
     /** Creates new form spp */
    public spp() {
        initComponents();
        tampilJurusan ();
        tampilSiswa ();
        tampilPembayaran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combox_pembayaran = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        nominal_pembayaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tahun_pembayaran = new javax.swing.JTextField();
        simpan_pembayaran = new javax.swing.JButton();
        new_pembayaran = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pembayaran = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nama_di_siswa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kelas_di_siswa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        combox_di_siswa = new javax.swing.JComboBox<>();
        simpan_di_siswa = new javax.swing.JButton();
        new_di_siswa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama_di_jurusan = new javax.swing.JTextField();
        simpan_jurusan = new javax.swing.JButton();
        new_jurusan = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_jurusan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Siswa");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        combox_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(combox_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        jLabel7.setText("Nominal");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel4.add(nominal_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        jLabel8.setText("Tahun");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel4.add(tahun_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        simpan_pembayaran.setText("Simpan");
        simpan_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_pembayaranActionPerformed(evt);
            }
        });
        jPanel4.add(simpan_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        new_pembayaran.setText("New");
        jPanel4.add(new_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        tabel_pembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Siswa", "Jurusan", "Nominal", "Tahun"
            }
        ));
        jScrollPane1.setViewportView(tabel_pembayaran);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 480, 240));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Pembayaran", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nama Lengkap");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(nama_di_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jLabel10.setText("Kelas");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel2.add(kelas_di_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel11.setText("Jurusan");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        combox_di_siswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(combox_di_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        simpan_di_siswa.setText("Simpan");
        simpan_di_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_di_siswaActionPerformed(evt);
            }
        });
        jPanel2.add(simpan_di_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 30));

        new_di_siswa.setText("New");
        jPanel2.add(new_di_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Kelas", "Jurusan"
            }
        ));
        jScrollPane3.setViewportView(tabel_siswa);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 480, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Siswa", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Jurusan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(nama_di_jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        simpan_jurusan.setText("Simpan");
        simpan_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_jurusanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan_jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        new_jurusan.setText("New");
        jPanel1.add(new_jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        tabel_jurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "No", "Nama"
            }
        ));
        jScrollPane4.setViewportView(tabel_jurusan);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 480, 240));

        jTabbedPane1.addTab("Jurusan", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 600, 270));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PEMBAYARAN SPP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_jurusanActionPerformed
        insertJurusan();
    }//GEN-LAST:event_simpan_jurusanActionPerformed

    private void simpan_di_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_di_siswaActionPerformed
        insertSiswa();
    }//GEN-LAST:event_simpan_di_siswaActionPerformed

    private void simpan_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_pembayaranActionPerformed
        insertPembayaran();
    }//GEN-LAST:event_simpan_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox_di_siswa;
    private javax.swing.JComboBox<String> combox_pembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField kelas_di_siswa;
    private javax.swing.JTextField nama_di_jurusan;
    private javax.swing.JTextField nama_di_siswa;
    private javax.swing.JButton new_di_siswa;
    private javax.swing.JButton new_jurusan;
    private javax.swing.JButton new_pembayaran;
    private javax.swing.JTextField nominal_pembayaran;
    private javax.swing.JButton simpan_di_siswa;
    private javax.swing.JButton simpan_jurusan;
    private javax.swing.JButton simpan_pembayaran;
    private javax.swing.JTable tabel_jurusan;
    private javax.swing.JTable tabel_pembayaran;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField tahun_pembayaran;
    // End of variables declaration//GEN-END:variables

    private void tampilJurusan() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_jurusan.getModel();
        data.setRowCount(0);
        combox_di_siswa.removeAllItems();
        try {
            String sql = "SELECT * FROM jurusan";
            Connection con = (Connection) koneksi.configDB();
            ResultSet res = con.createStatement().executeQuery(sql);
            int a=0;
           while (res.next()) {
                data.addRow(new Object[] {res.getString(1), res.getString(2)});
                combox_di_siswa.addItem(res.getString(2));
                idJurusan.put(a, res.getString(1));
                a++;
            }
            tabel_jurusan.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tampilSiswa() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_siswa.getModel();
        
        try {
            String sql = "SELECT S.id ,S.nama_lengkap ,S.kelas ,J.nama_jurusan  FROM siswa AS S JOIN jurusan AS J ON J.id= S.id_jurusan";
            Connection con = (Connection) koneksi.configDB();
            ResultSet res = con.createStatement().executeQuery(sql);
            
           while (res.next()) {
                data.addRow(new Object[] {res.getString(1), res.getString(2),res.getString(3), res.getString(4)});
            }
            tabel_siswa.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tampilPembayaran() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_pembayaran.getModel();
        data.setRowCount(0);
        try {
            String sql = "SELECT S.id ,S.nama_lengkap ,J.nama_jurusan,"
                    + " SP.nominal,SP.tahun   FROM spp AS SP"
                    + " JOIN siswa AS S ON S.id= SP.id_siswa "
                    + "JOIN jurusan AS J ON J.id=S.id_jurusan";
            Connection con = (Connection) koneksi.configDB();
            ResultSet res = con.createStatement().executeQuery(sql);
            
           while (res.next()) {
                data.addRow(new Object[] {
                res.getString(1), res.getString(2),
                res.getString(3), res.getString(4),
                res.getString(5)
                });
            }
            tabel_pembayaran.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void insertJurusan() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_jurusan.getModel();
        
        try {
            String sql = "INSERT INTO jurusan(id, nama_jurusan) VALUES (null, '"+ nama_di_jurusan.getText()+ "')";
            Connection con = (Connection) koneksi.configDB();
            int res = con.createStatement().executeUpdate(sql);
            
           if (res > -1) {
                tampilJurusan();
                nama_di_jurusan.setText("");
                JOptionPane.showMessageDialog(null, "Data Jurusan Berhasil di Input");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     private void insertSiswa() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_siswa.getModel();
        
        try {
            String sql = "INSERT INTO siswa(id, nama_lengkap, kelas,id_jurusan)"
                    + " VALUES (null, '"+ nama_di_siswa.getText()+ "',"
                    + "'"+nama_di_siswa.getText() +"',"
                    + "'"+idJurusan.get(combox_di_siswa.getSelectedIndex()) +"')";
            Connection con = (Connection) koneksi.configDB();
            int res = con.createStatement().executeUpdate(sql);
            
           if (res > -1) {
                tampilSiswa();
                nama_di_siswa.setText("");
                kelas_di_siswa.setText("");
                combox_di_siswa.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "Data Siswa Berhasil di Input");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     private void insertPembayaran() {
        
        DefaultTableModel data = (DefaultTableModel) tabel_pembayaran.getModel();
        
        try {
            String sql = "INSERT INTO spp(id, nominal, tahun) VALUES (null, '"+ nominal_pembayaran.getText()+ "')";
            Connection con = (Connection) koneksi.configDB();
            int res = con.createStatement().executeUpdate(sql);
            
           if (res > -1) {
                tampilPembayaran();
                nominal_pembayaran.setText("");
                JOptionPane.showMessageDialog(null, "Data SPP`   Berhasil di Input");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
